/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameStateBodySchema {
  key: string;
  description: string;
  date: string;
  winningPlayerKey: string;
  duration?: number | null;
  playerNamesForDisplay?: string | null;
  players: Player[];
  settings?: Settings | null;
  scoreHistory: {
    [k: string]: PlayerScoreHistory;
  };
}
export interface Player {
  key: string;
  name: string;
}
export interface Settings {
  key: string;
  gameKey: string;
  startingScore?: number;
  defaultScoreStep?: number;
  highScoreWins: boolean;
}
export interface PlayerScoreHistory {
  key: string;
  gameKey?: string;
  playerKey: string;
  scores: number[];
  currentScore: number;
}
